const SET_BOOKS = "SET_BOOKS";
const GET_BOOKS = "GET_BOOKS";
const ADD_BOOK  = "ADD_BOOK";
const LOAD_BOOKS = "LOAD_BOOKS";
const SET_FILTER = "SET_FILTER";
const SEARCH_BOOKS = "SEARCH_BOOKS";
const SORT_BOOKS = "SORT_BOOKS"
const EDIT_BOOK = "EDIT_BOOK";

export {SET_BOOKS, GET_BOOKS, ADD_BOOK, LOAD_BOOKS, SET_FILTER, SEARCH_BOOKS, SORT_BOOKS, EDIT_BOOK}